name: test

on:
  push:
  schedule:
    # At 06:00am every Saturday (for new versions of rustc)
    - cron:  '0 6 * * 6'

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: install stable
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    # Build check --------------------------------------------------------------

    - name: build --all-targets
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all-targets

    # Test runners -------------------------------------------------------------

    - name: test
      uses: actions-rs/cargo@v1
      with:
        command: test

    - name: test --all-features
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features

    # Example runners ----------------------------------------------------------

    - name: run --example static_strs
      uses: actions-rs/cargo@v1
      with:
        command: run
        args: --example static_strs

    - name: run --example try_insert
      uses: actions-rs/cargo@v1
      with:
        command: run
        args: --example try_insert